version: '3.8'

services:
  bilkent-api:
    build: .
    container_name: bilkent-api
    ports:
      - "${APP_PORT}:8080"
    depends_on:
      - redis
    environment:
      SPRING_DATA_REDIS_HOST: ${SPRING_DATA_REDIS_HOST}
      SPRING_DATA_REDIS_PORT: ${SPRING_DATA_REDIS_PORT}

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "${SPRING_DATA_REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  redis_data:
